/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExtensionRouteImport } from './routes/_authenticated/extension'
import { Route as AuthenticatedPipelineRouteImport } from './routes/_authenticated/pipeline'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as ApiExtensionCodeRouteImport } from './routes/api/extension/code'
import { Route as ApiPublicClaimRouteImport } from './routes/api/public/claim'
import { Route as ApiPublicClaudeRouteImport } from './routes/api/public/claude'
import { Route as ApiPublicGeminiRouteImport } from './routes/api/public/gemini'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicSyncActivityRouteImport } from './routes/api/public/sync/activity'
import { Route as ApiPublicSyncFingerprintsRouteImport } from './routes/api/public/sync/fingerprints'
import { Route as ApiPublicSyncLeadRouteImport } from './routes/api/public/sync/lead'
import { Route as ApiPublicSyncMessageRouteImport } from './routes/api/public/sync/message'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExtensionRoute = AuthenticatedExtensionRouteImport.update({
  id: '/extension',
  path: '/extension',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPipelineRoute = AuthenticatedPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiExtensionCodeRoute = ApiExtensionCodeRouteImport.update({
  id: '/api/extension/code',
  path: '/api/extension/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaimRoute = ApiPublicClaimRouteImport.update({
  id: '/api/public/claim',
  path: '/api/public/claim',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClaudeRoute = ApiPublicClaudeRouteImport.update({
  id: '/api/public/claude',
  path: '/api/public/claude',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicGeminiRoute = ApiPublicGeminiRouteImport.update({
  id: '/api/public/gemini',
  path: '/api/public/gemini',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncActivityRoute = ApiPublicSyncActivityRouteImport.update({
  id: '/api/public/sync/activity',
  path: '/api/public/sync/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncFingerprintsRoute =
  ApiPublicSyncFingerprintsRouteImport.update({
    id: '/api/public/sync/fingerprints',
    path: '/api/public/sync/fingerprints',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncLeadRoute = ApiPublicSyncLeadRouteImport.update({
  id: '/api/public/sync/lead',
  path: '/api/public/sync/lead',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncMessageRoute = ApiPublicSyncMessageRouteImport.update({
  id: '/api/public/sync/message',
  path: '/api/public/sync/message',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/extension/code': typeof ApiExtensionCodeRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/claude': typeof ApiPublicClaudeRoute
  '/api/public/gemini': typeof ApiPublicGeminiRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sync/activity': typeof ApiPublicSyncActivityRoute
  '/api/public/sync/fingerprints': typeof ApiPublicSyncFingerprintsRoute
  '/api/public/sync/lead': typeof ApiPublicSyncLeadRoute
  '/api/public/sync/message': typeof ApiPublicSyncMessageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/extension': typeof AuthenticatedExtensionRoute
  '/pipeline': typeof AuthenticatedPipelineRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/api/extension/code': typeof ApiExtensionCodeRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/claude': typeof ApiPublicClaudeRoute
  '/api/public/gemini': typeof ApiPublicGeminiRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sync/activity': typeof ApiPublicSyncActivityRoute
  '/api/public/sync/fingerprints': typeof ApiPublicSyncFingerprintsRoute
  '/api/public/sync/lead': typeof ApiPublicSyncLeadRoute
  '/api/public/sync/message': typeof ApiPublicSyncMessageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/extension': typeof AuthenticatedExtensionRoute
  '/_authenticated/pipeline': typeof AuthenticatedPipelineRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/api/extension/code': typeof ApiExtensionCodeRoute
  '/api/public/claim': typeof ApiPublicClaimRoute
  '/api/public/claude': typeof ApiPublicClaudeRoute
  '/api/public/gemini': typeof ApiPublicGeminiRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/sync/activity': typeof ApiPublicSyncActivityRoute
  '/api/public/sync/fingerprints': typeof ApiPublicSyncFingerprintsRoute
  '/api/public/sync/lead': typeof ApiPublicSyncLeadRoute
  '/api/public/sync/message': typeof ApiPublicSyncMessageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/extension'
    | '/pipeline'
    | '/settings'
    | '/api/extension/code'
    | '/api/public/claim'
    | '/api/public/claude'
    | '/api/public/gemini'
    | '/api/public/health'
    | '/api/public/sync/activity'
    | '/api/public/sync/fingerprints'
    | '/api/public/sync/lead'
    | '/api/public/sync/message'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/reset-password'
    | '/analytics'
    | '/dashboard'
    | '/extension'
    | '/pipeline'
    | '/settings'
    | '/api/extension/code'
    | '/api/public/claim'
    | '/api/public/claude'
    | '/api/public/gemini'
    | '/api/public/health'
    | '/api/public/sync/activity'
    | '/api/public/sync/fingerprints'
    | '/api/public/sync/lead'
    | '/api/public/sync/message'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/reset-password'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/extension'
    | '/_authenticated/pipeline'
    | '/_authenticated/settings'
    | '/api/extension/code'
    | '/api/public/claim'
    | '/api/public/claude'
    | '/api/public/gemini'
    | '/api/public/health'
    | '/api/public/sync/activity'
    | '/api/public/sync/fingerprints'
    | '/api/public/sync/lead'
    | '/api/public/sync/message'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiExtensionCodeRoute: typeof ApiExtensionCodeRoute
  ApiPublicClaimRoute: typeof ApiPublicClaimRoute
  ApiPublicClaudeRoute: typeof ApiPublicClaudeRoute
  ApiPublicGeminiRoute: typeof ApiPublicGeminiRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicSyncActivityRoute: typeof ApiPublicSyncActivityRoute
  ApiPublicSyncFingerprintsRoute: typeof ApiPublicSyncFingerprintsRoute
  ApiPublicSyncLeadRoute: typeof ApiPublicSyncLeadRoute
  ApiPublicSyncMessageRoute: typeof ApiPublicSyncMessageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/extension': {
      id: '/_authenticated/extension'
      path: '/extension'
      fullPath: '/extension'
      preLoaderRoute: typeof AuthenticatedExtensionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pipeline': {
      id: '/_authenticated/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof AuthenticatedPipelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/extension/code': {
      id: '/api/extension/code'
      path: '/api/extension/code'
      fullPath: '/api/extension/code'
      preLoaderRoute: typeof ApiExtensionCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/claim': {
      id: '/api/public/claim'
      path: '/api/public/claim'
      fullPath: '/api/public/claim'
      preLoaderRoute: typeof ApiPublicClaimRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/claude': {
      id: '/api/public/claude'
      path: '/api/public/claude'
      fullPath: '/api/public/claude'
      preLoaderRoute: typeof ApiPublicClaudeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/gemini': {
      id: '/api/public/gemini'
      path: '/api/public/gemini'
      fullPath: '/api/public/gemini'
      preLoaderRoute: typeof ApiPublicGeminiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/activity': {
      id: '/api/public/sync/activity'
      path: '/api/public/sync/activity'
      fullPath: '/api/public/sync/activity'
      preLoaderRoute: typeof ApiPublicSyncActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/fingerprints': {
      id: '/api/public/sync/fingerprints'
      path: '/api/public/sync/fingerprints'
      fullPath: '/api/public/sync/fingerprints'
      preLoaderRoute: typeof ApiPublicSyncFingerprintsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/lead': {
      id: '/api/public/sync/lead'
      path: '/api/public/sync/lead'
      fullPath: '/api/public/sync/lead'
      preLoaderRoute: typeof ApiPublicSyncLeadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/message': {
      id: '/api/public/sync/message'
      path: '/api/public/sync/message'
      fullPath: '/api/public/sync/message'
      preLoaderRoute: typeof ApiPublicSyncMessageRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExtensionRoute: typeof AuthenticatedExtensionRoute
  AuthenticatedPipelineRoute: typeof AuthenticatedPipelineRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExtensionRoute: AuthenticatedExtensionRoute,
  AuthenticatedPipelineRoute: AuthenticatedPipelineRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiExtensionCodeRoute: ApiExtensionCodeRoute,
  ApiPublicClaimRoute: ApiPublicClaimRoute,
  ApiPublicClaudeRoute: ApiPublicClaudeRoute,
  ApiPublicGeminiRoute: ApiPublicGeminiRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicSyncActivityRoute: ApiPublicSyncActivityRoute,
  ApiPublicSyncFingerprintsRoute: ApiPublicSyncFingerprintsRoute,
  ApiPublicSyncLeadRoute: ApiPublicSyncLeadRoute,
  ApiPublicSyncMessageRoute: ApiPublicSyncMessageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
